### ISSUE TITLE
master branch with bloom configuration missing for this repository

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2-gbp/zbar_ros-release#1]
@ijnek truth be told I'm not entirely sure how we got here but the `master` branch for this repository which contains the bloom configuration is missing and that is blocking migrating this package to humble.

Do you have another copy of this repository either locally or in another organization or should I check with GitHub support to see if there's a backup of that ref?

**Comment by ijnek** [comment]
@nuclearsandwich That's strange, but no worries. I don't have a backup of the repository anywhere.
I don't mind making a new release if that's an easy solution.

**Comment by ijnek** [comment]
I take that back, I see where the issue happened, in https://github.com/ros/rosdistro/pull/32228.

The old release repo (ros-drivers-gbp/zbar_ros-release) was used for the ``0.4.0-1`` release, but then the rosdistro PR was [edited manually](https://github.com/ros/rosdistro/pull/32228/commits/8815114208c472dac095e57d5195b8c151000cfb) to point to the release repo on ros2-gbp. For some reason, the master branch didn't port across correctly when ros2-gbp/zbar_ros-release was created.

I'm going to port the master branch across from https://github.com/ros-drivers-gbp/zbar_ros-release

**Comment by ijnek** [comment]
@nuclearsandwich Done, https://github.com/ros2-gbp/zbar_ros-release/tree/master.
Please tell me if more action is required.

**Comment by ijnek** [comment]
Closing, as this seems to be resolved.

**Comment by nuclearsandwich** [comment]
@ijnek thanks for taking a look and diagnosing the issue!
